services:
  db:
    image: postgres:16
    container_name: aadhirai_pharma
    environment:
      POSTGRES_DB: aadhirai_pharma_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d aadhirai_pharma_db"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  pgdata: