import { z } from "zod";

const taxModeSchema = z.enum(["INCLUSIVE", "EXCLUSIVE"]).default("EXCLUSIVE");

export const salePostingLineSchema = z.object({
  medicineId: z.number().int().positive(),
  medicineName: z.string().min(1),
  batchNumber: z.string().optional(),
  expiryDate: z.string().optional(),
  hsnCode: z.string().nullable().optional(),
  soldQty: z.number().nonnegative().optional(),
  soldQtyBase: z.number().int().nonnegative().optional(),
  quantity: z.number().int().nonnegative().optional(),
  conversionFactorSnapshot: z.number().int().positive().optional(),
  unitType: z.string().optional(),
  packSize: z.number().int().positive().optional(),
  price: z.union([z.string(), z.number()]).transform((value) => String(value)),
  mrp: z.union([z.string(), z.number()]).nullable().optional().transform((value) => (value == null ? null : String(value))),
  gstRate: z.union([z.string(), z.number()]).optional().transform((value) => (value == null ? undefined : String(value))),
  cgst: z.union([z.string(), z.number()]).optional().transform((value) => (value == null ? undefined : String(value))),
  sgst: z.union([z.string(), z.number()]).optional().transform((value) => (value == null ? undefined : String(value))),
  discount: z.union([z.string(), z.number()]).optional().transform((value) => (value == null ? undefined : String(value))),
  total: z.union([z.string(), z.number()]).optional().transform((value) => (value == null ? undefined : String(value))),
  taxMode: taxModeSchema.optional(),
});

export const salePostingRequestSchema = z.object({
  customerId: z.number().int().positive().nullable().optional(),
  customerName: z.string().min(1),
  customerPhone: z.string().nullable().optional(),
  customerGstin: z.string().nullable().optional(),
  doctorId: z.number().int().positive().nullable().optional(),
  doctorName: z.string().nullable().optional(),
  subtotal: z.union([z.string(), z.number()]).transform((value) => String(value)),
  discount: z.union([z.string(), z.number()]).transform((value) => String(value)),
  discountPercent: z.union([z.string(), z.number()]).transform((value) => String(value)),
  cgst: z.union([z.string(), z.number()]).transform((value) => String(value)),
  sgst: z.union([z.string(), z.number()]).transform((value) => String(value)),
  tax: z.union([z.string(), z.number()]).transform((value) => String(value)),
  total: z.union([z.string(), z.number()]).transform((value) => String(value)),
  roundOff: z.union([z.string(), z.number()]).optional().transform((value) => (value == null ? undefined : String(value))),
  paymentMethod: z.string().min(1),
  paymentReference: z.string().nullable().optional(),
  receivedAmount: z.union([z.string(), z.number()]).optional().transform((value) => (value == null ? undefined : String(value))),
  changeAmount: z.union([z.string(), z.number()]).optional().transform((value) => (value == null ? undefined : String(value))),
  status: z.string().optional(),
  printInvoice: z.boolean().optional(),
  sendViaEmail: z.boolean().optional(),
  userId: z.string().nullable().optional(),
  items: z.array(salePostingLineSchema).min(1),
});

export const grnPostingLineSchema = z.object({
  poLineId: z.number().int().positive().nullable().optional(),
  poItemId: z.number().int().positive().nullable().optional(),
  medicineId: z.number().int().positive(),
  medicineName: z.string().min(1),
  batchNumber: z.string().min(1),
  expiryDate: z.string().min(1),
  receivedQty: z.number().nonnegative(),
  freeQty: z.number().nonnegative().optional(),
  quantity: z.number().nonnegative().optional(),
  freeQuantity: z.number().nonnegative().optional(),
  conversionFactorSnapshot: z.number().int().positive().optional(),
  purchaseUnit: z.string().optional(),
  unitsPerStrip: z.number().int().positive().optional(),
  rate: z.union([z.string(), z.number()]).transform((value) => String(value)),
  ptr: z.union([z.string(), z.number()]).nullable().optional().transform((value) => (value == null ? null : String(value))),
  sellingPrice: z.union([z.string(), z.number()]).nullable().optional().transform((value) => (value == null ? null : String(value))),
  mrp: z.union([z.string(), z.number()]).nullable().optional().transform((value) => (value == null ? null : String(value))),
  discountPercent: z.union([z.string(), z.number()]).optional().transform((value) => (value == null ? undefined : String(value))),
  discountAmount: z.union([z.string(), z.number()]).optional().transform((value) => (value == null ? undefined : String(value))),
  gstRate: z.union([z.string(), z.number()]).optional().transform((value) => (value == null ? undefined : String(value))),
  taxAmount: z.union([z.string(), z.number()]).optional().transform((value) => (value == null ? undefined : String(value))),
  totalAmount: z.union([z.string(), z.number()]).optional().transform((value) => (value == null ? undefined : String(value))),
  taxMode: taxModeSchema.optional(),
  locationId: z.number().int().positive().nullable().optional(),
});

export const grnPostingRequestSchema = z.object({
  grnNumber: z.string().min(1),
  poId: z.number().int().positive().nullable().optional(),
  supplierId: z.number().int().positive(),
  supplierName: z.string().min(1),
  supplierInvoiceNo: z.string().nullable().optional(),
  supplierInvoiceDate: z.string().nullable().optional(),
  receiptDate: z.string().nullable().optional(),
  status: z.string().optional(),
  subtotal: z.union([z.string(), z.number()]).transform((value) => String(value)),
  discountRate: z.union([z.string(), z.number()]).optional().transform((value) => (value == null ? undefined : String(value))),
  discountAmount: z.union([z.string(), z.number()]).optional().transform((value) => (value == null ? undefined : String(value))),
  taxAmount: z.union([z.string(), z.number()]).transform((value) => String(value)),
  totalAmount: z.union([z.string(), z.number()]).transform((value) => String(value)),
  notes: z.string().nullable().optional(),
  receivedBy: z.string().nullable().optional(),
  updateSkuDefaultPricingFromGrn: z.boolean().optional(),
  allowExcessReceipt: z.boolean().optional(),
  items: z.array(grnPostingLineSchema).min(1),
});

export type SalePostingRequest = z.infer<typeof salePostingRequestSchema>;
export type GrnPostingRequest = z.infer<typeof grnPostingRequestSchema>;
